import Link from "next/link";
import { Figure, H2, P } from "../science/Figure";
import { FIG } from "@/lib/fig";
import { HeadProfile } from "../anatomy/HeadProfile";

const link =
  "text-teal-700 underline decoration-slate-300 underline-offset-2 hover:decoration-teal-600";

/**
 * Figure 1 — the four phases of a migraine attack, with the pain as one
 * chapter of a longer neurological event.
 */
function PhasesFigure() {
  const bands = [
    { x: 40, w: 150, name: "Prodrome", time: "hours–a day before", fill: FIG.ground },
    { x: 190, w: 70, name: "Aura", time: "20–60 min", fill: FIG.nerveTint },
    { x: 260, w: 240, name: "Headache", time: "4–72 hours", fill: FIG.signalGround },
    { x: 500, w: 140, name: "Postdrome", time: "up to a day after", fill: FIG.ground },
  ];
  return (
    <Figure caption="A migraine attack in four phases (widths not to scale). The headache is the loudest chapter — but the attack often starts a day earlier and ends a day later, which is why 'just take something for the headache' misreads the disease.">
      <svg
        role="img"
        aria-labelledby="ph-title ph-desc"
        viewBox="0 0 680 300"
        className="mx-auto block h-auto w-full max-w-2xl"
      >
        <title id="ph-title">The four phases of a migraine attack</title>
        <desc id="ph-desc">
          A timeline divided into prodrome (hours to a day before), aura
          (twenty to sixty minutes, in about one in three people), headache
          (four to seventy-two hours), and postdrome (up to a day after). An
          amber intensity curve stays low through the early phases, peaks
          during the headache, and settles through the postdrome.
        </desc>

        {bands.map((b) => (
          <g key={b.name}>
            <rect x={b.x} y="80" width={b.w} height="150" fill={b.fill} />
            <text x={b.x + b.w / 2} y="48" textAnchor="middle" fontSize="14" fontWeight="700" fill={FIG.ink}>
              {b.name}
            </text>
            <text x={b.x + b.w / 2} y="66" textAnchor="middle" fontSize="11" fill={FIG.muted}>
              {b.time}
            </text>
          </g>
        ))}
        <line x1="40" y1="230" x2="640" y2="230" stroke={FIG.faint} strokeWidth="1.5" />

        {/* intensity curve */}
        <path
          d="M40 215 C90 213 140 208 190 205 C213 203 235 201 260 198 C300 130 340 105 385 105 C430 105 462 160 500 195 C540 214 590 217 640 217"
          fill="none"
          stroke={FIG.signalDark}
          strokeWidth="3.5"
          strokeLinecap="round"
        />

        {/* staggered phase notes */}
        <g fontSize="11.5" fill={FIG.textMid} textAnchor="middle">
          <text x="115" y="258">yawning, cravings, mood shifts</text>
          <text x="380" y="258">throbbing pain — light, sound, movement hurt</text>
          <text x="225" y="280">shimmering zigzags — 1 in 3 people</text>
          <text x="565" y="280">fog and fatigue — the hangover</text>
        </g>
      </svg>
    </Figure>
  );
}

/**
 * Figure 2 — the trigeminovascular engine: where the pain is felt, and the
 * nerve-and-peptide machinery generating it. HeadProfile's first page use.
 */
function EngineFigure() {
  return (
    <Figure caption="Where migraine lives: pain classically one-sided, behind the eye and at the temple — generated by the trigeminal nerve releasing CGRP onto the brain's pain-sensitive coverings. That peptide is the target the new drugs were designed to block.">
      <svg
        role="img"
        aria-labelledby="eng-title eng-desc"
        viewBox="0 0 680 320"
        className="mx-auto block h-auto w-full max-w-2xl"
      >
        <title id="eng-title">The migraine engine</title>
        <desc id="eng-desc">
          A head in profile with amber pain markers at the temple and behind
          the eye. A teal trigeminal nerve fans forward from a ganglion near
          the ear toward the eye, temple, and jaw. Labels identify the felt
          pain and the nerve-and-CGRP machinery behind it.
        </desc>

        <g transform="translate(36 16)">
          <HeadProfile marks={[{ at: "temple", size: "md" }, { at: "orbit", size: "sm" }]}>
            {/* trigeminal ganglion + three branches */}
            <circle cx="150" cy="138" r="7" fill={FIG.nerveTint} stroke={FIG.nerveDark} strokeWidth="2" />
            <g fill="none" stroke={FIG.nerve} strokeWidth="3" strokeLinecap="round">
              <path d="M150 138 C130 126 102 112 84 108" />
              <path d="M150 138 C138 120 120 104 108 98" />
              <path d="M150 138 C136 156 122 166 110 170" />
            </g>
          </HeadProfile>
        </g>

        <g fontSize="15" fontWeight="700" fill={FIG.ink}>
          <text x="340" y="86">The pain</text>
          <text x="340" y="210">The engine</text>
        </g>
        <g fontSize="12.5" fill={FIG.textMid}>
          <text x="340" y="106">classically one-sided and throbbing —</text>
          <text x="340" y="123">often behind the eye and at the temple</text>
          <text x="340" y="230">the trigeminal nerve releases CGRP onto</text>
          <text x="340" y="247">the brain&rsquo;s pain-sensitive coverings —</text>
          <text x="340" y="264">the target of the antibodies and gepants</text>
        </g>
        <g stroke={FIG.line} strokeWidth="1.5" fill="none">
          <path d="M332 100 Q240 108 152 112" />
          <path d="M332 226 Q260 210 196 160" />
        </g>
      </svg>
    </Figure>
  );
}

export default function Migraine() {
  return (
    <div>
      <P>
        Migraine may be the most consequential disease that people are still
        told to walk off. It affects roughly <strong>one person in
        seven</strong> — about a billion people — runs strongly in families,
        and in the Global Burden of Disease studies ranks{" "}
        <strong>second among all causes of disability on Earth, and first
        among young women</strong>, who live with it at three times the rate
        of men. None of that describes &ldquo;a bad headache.&rdquo; It
        describes a neurological disease with its own machinery — machinery
        that science has now traced well enough to build drugs against,
        which is why migraine has become pain medicine&rsquo;s biggest
        recent success story.
      </P>

      <H2 id="phases">An attack is more than a headache</H2>
      <PhasesFigure />
      <P>
        A migraine attack is a sequence, and the headache is its loudest
        middle chapter. Many attacks announce themselves a day early in the{" "}
        <strong>prodrome</strong> — yawning, food cravings, mood shifts,
        neck stiffness — driven by deep brain regions like the hypothalamus
        waking up first. About one in three people then experience{" "}
        <strong>aura</strong>: a slow electrical wave crossing the
        brain&rsquo;s surface, felt most often as shimmering zigzags or a
        growing blind spot that spreads over twenty to sixty minutes before
        fading. The <strong>headache phase</strong> brings the signature:
        throbbing, often one-sided pain lasting hours to days, with a
        nervous system so amplified that light, sound, smells, and ordinary
        movement all hurt. And then the <strong>postdrome</strong> — the
        migraine hangover of fog and fatigue that costs many people another
        day. The prodrome hides a useful insight: some famous
        &ldquo;triggers&rdquo; are really early symptoms. Craving chocolate
        may not cause the attack — the attack, already underway, may be
        causing the craving.
      </P>

      <H2 id="engine">The engine: a nerve, a peptide, a sensitive brain</H2>
      <EngineFigure />
      <P>
        For most of a century migraine was blamed on blood vessels
        stretching. The modern picture is neurological. The inherited part
        is a brain whose sensory networks sit closer to their tipping point.
        The attack part is traceable: the <strong>trigeminal nerve</strong>
        — the great sensory nerve of the head — activates and releases{" "}
        <strong>CGRP</strong>, a peptide that inflames the brain&rsquo;s
        pain-sensitive coverings and drives the throbbing, movement-hating
        pain, while brainstem and thalamic circuits amplify every other
        sense. That specificity is the story: CGRP is not a metaphor but a
        molecule, and blocking it works — the arc told in full in{" "}
        <Link href="/future-of-pain-medicine/biologics-and-gene-therapy" className={link}>
          biologics &amp; gene-targeted therapy
        </Link>
        .
      </P>

      <H2 id="triggers">Triggers, honestly</H2>
      <P>
        Trigger lists are where migraine advice usually goes to die —
        everything from weather to wine gets blamed, and patients end up
        policing their lives. The evidence supports a humbler model:
        triggers are probabilistic, they stack, and they act on a brain
        whose threshold is already set by sleep, stress, hormones, and
        routine. The highest-yield moves are unglamorous:{" "}
        <strong>regularity</strong> — of sleep, meals, hydration, caffeine,
        and exercise — raises the threshold an attack has to clear.{" "}
        <Link href="/understanding-pain/pain-and-sleep" className={link}>
          Sleep
        </Link>{" "}
        earns special mention: it is one of the few levers with mechanism
        and evidence on its side. A simple diary beats an internet trigger
        list — it finds <em>your</em> pattern, and sometimes reveals that a
        supposed trigger was the prodrome all along.
      </P>

      <H2 id="diagnosis">How it&rsquo;s diagnosed — and the red flags</H2>
      <P>
        Migraine is a clinical diagnosis — there is no blood test or scan
        that shows it. The international criteria look for the pattern:
        attacks lasting hours to days, pain that throbs and favors one
        side, worsens with routine movement, and travels with nausea or
        with sensitivity to light and sound. A typical story needs no
        imaging. What changes the calculus are the red flags: a{" "}
        <strong>thunderclap</strong> headache reaching full force in
        seconds, a first severe headache after fifty, fever with a stiff
        neck, aura-like symptoms that include weakness or trouble speaking,
        symptoms that arrive suddenly rather than marching gradually, or a
        long-stable pattern that transforms. Those earn urgent evaluation —
        everything else earns a proper migraine plan.
      </P>

      <H2 id="treatment">How migraine is treated today</H2>
      <P>
        Acute treatment is a race: medications work best taken{" "}
        <strong>early</strong>, while the attack is still building.
        Anti-inflammatory painkillers genuinely help many attacks; the{" "}
        <strong>triptans</strong> — the first drugs ever designed from
        migraine&rsquo;s biology, back in the 1990s — remain the workhorses;
        and the newer <strong>gepants</strong> and{" "}
        <strong>lasmiditan</strong> cover people whose attacks laugh at
        triptans or whose hearts shouldn&rsquo;t meet them. Opioids,
        deliberately, have almost no place in routine migraine care. And one
        honest warning belongs in bold type: acute relief used on too many
        days a month, for months, can flip episodic migraine into a
        near-daily <strong>medication-overuse headache</strong> that the
        same pills no longer touch. Counting days is not pedantry — it is
        how you keep your rescue medicines working.
      </P>
      <P>
        Prevention is where the revolution happened. When attacks claim
        several days a month, guidelines shift from rescuing to preventing:
        long-standing oral options — blood-pressure, seizure, and
        antidepressant medications with earned migraine evidence — plus, for
        chronic migraine, botulinum toxin injections. Since 2018 they have
        been joined by the <strong>CGRP monoclonal antibodies</strong> —
        monthly or quarterly injections that lower attack frequency with
        strikingly little side-effect baggage — and{" "}
        <strong>preventive gepants</strong> in tablet form. For many people
        these are the first treatments that feel designed for their disease,
        because they were. Which of any of this fits you — including
        wearable neuromodulation devices for those who prefer hardware to
        pharmacology — is a plan to build with your clinician, not a menu to
        self-serve.
      </P>

      <H2 id="whats-coming">What&rsquo;s coming</H2>
      <P>
        The CGRP era proved that decoding a mechanism yields drugs; the
        field is now working the next peptides, with{" "}
        <strong>PACAP</strong>-blocking antibodies furthest along in trials
        for people CGRP drugs miss. The{" "}
        <Link href="/future-of-pain-medicine/pipeline" className={link}>
          pipeline tracker
        </Link>{" "}
        follows the candidates; migraine research remains the clearest
        demonstration in all of pain medicine that the frontier pays out.
      </P>

      <H2 id="specialist">When to bring in a specialist</H2>
      <P>
        If migraine is costing you multiple days a month despite a fair
        acute-treatment plan, if prevention has never been discussed, or if
        you suspect the medication-overuse trap has already closed —
        that is the moment for{" "}
        <Link href="/what-is-pain-medicine" className={link}>
          specialist care
        </Link>
        : headache medicine and pain medicine both live here.{" "}
        <Link href="/find-help" className={link}>
          Finding pain care near you
        </Link>{" "}
        explains how to start looking.
      </P>
    </div>
  );
}
